env:
  node: true

plugins:
  - 'jest'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  comma-dangle: off
  implicit-arrow-linebreak: off
  class-methods-use-this: off
  function-paren-newline: off
